#!/usr/bin/env python3
"""
Sync MCP servers from this repo's servers.json to:
1. $CODEX_HOME/mcp.generated.toml (or ~/.codex/mcp.generated.toml)
2. Codex user config.toml (merge into a marked block, never overwrite other content)

servers.json lives next to this script (the mcp repo checkout).

Config path resolution (first match wins):
- $CODEX_CONFIG — absolute path to config.toml
- $CODEX_HOME/config.toml — Codex default data dir (see OpenAI Codex docs)
- ~/.codex/config.toml
"""
import json
import os
import re
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent
SRC = REPO_ROOT / "servers.json"


def codex_config_path() -> Path:
    if p := os.environ.get("CODEX_CONFIG"):
        return Path(p).expanduser()
    if home := os.environ.get("CODEX_HOME"):
        return Path(home).expanduser() / "config.toml"
    return Path.home() / ".codex/config.toml"


def codex_generated_toml_path() -> Path:
    if home := os.environ.get("CODEX_HOME"):
        return Path(home).expanduser() / "mcp.generated.toml"
    return Path.home() / ".codex/mcp.generated.toml"


BEGIN_MARKER = "# BEGIN MCP SYNC (from servers.json)"
END_MARKER = "# END MCP SYNC"


def toml_quote(s: str) -> str:
    return '"' + s.replace('\\', '\\\\').replace('"', '\\"') + '"'


def toml_bare_key_segment(s: str) -> bool:
    """True if s is valid as an unquoted TOML key segment (letters, digits, _, -)."""
    return bool(re.fullmatch(r"[A-Za-z0-9_-]+", s))


def toml_header_key_segment(s: str) -> str:
    """Quote a table-header segment when it contains spaces, dots, or other special chars."""
    return s if toml_bare_key_segment(s) else toml_quote(s)


def toml_array(items):
    return "[" + ", ".join(toml_quote(x) for x in items) + "]"


def generate_toml(servers: dict) -> str:
    lines = []
    lines.append(f"# AUTOGENERATED from {SRC}")
    lines.append("")
    for name, cfg in servers.items():
        key = toml_header_key_segment(name)
        lines.append(f"[mcp_servers.{key}]")
        if "url" in cfg:
            lines.append(f"url = {toml_quote(cfg['url'])}")
        else:
            lines.append(f"command = {toml_quote(cfg['command'])}")
            if "args" in cfg:
                lines.append(f"args = {toml_array(cfg['args'])}")
        env = cfg.get("env") or {}
        if env:
            lines.append("env = { " + ", ".join(f"{k} = {toml_quote(str(v))}" for k, v in env.items()) + " }")
        lines.append("")
    return "\n".join(lines).rstrip()


def merge_into_codex_config(generated: str) -> None:
    """Merge generated MCP TOML into config.toml via a marked block. Does not overwrite other content."""
    cfg = codex_config_path()
    block = f"\n{BEGIN_MARKER}\n{generated}\n{END_MARKER}\n"
    if not cfg.exists():
        cfg.parent.mkdir(parents=True, exist_ok=True)
        cfg.write_text(
            f"# Codex config\n# Add your settings above; MCP servers are synced below.\n{block}",
            encoding="utf-8",
        )
        print(f"Created {cfg} with MCP sync block.")
        return
    text = cfg.read_text(encoding="utf-8")
    pattern = re.compile(
        re.escape(BEGIN_MARKER) + r".*?" + re.escape(END_MARKER),
        re.DOTALL,
    )
    if pattern.search(text):
        # Do not rstrip(block): trailing newline must remain so content after the block stays valid TOML.
        new_text = pattern.sub(block, text)
        cfg.write_text(new_text, encoding="utf-8")
        print(f"Updated MCP sync block in {cfg}.")
    else:
        appended = text.rstrip() + "\n" + block
        cfg.write_text(appended, encoding="utf-8")
        print(f"Appended MCP sync block to {cfg}.")


def main():
    data = json.loads(SRC.read_text(encoding="utf-8"))
    servers = data.get("mcpServers", {})

    generated = generate_toml(servers)
    out = codex_generated_toml_path()
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(generated, encoding="utf-8")
    print(f"Wrote: {out}")

    merge_into_codex_config(generated)


if __name__ == "__main__":
    main()